sudo: false
language: node_js
node_js:
  - '8'
  - '9'
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS cnpmjs;'
  
install:
  - npm i npminstall && npminstall
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov

