sudo: false
os:
  - linux
  - osx
language: node_js
node_js:
  - '10'
install:
  - npm i npminstall && npminstall
script:
  - npm run init-and-ci
after_script:
  - npminstall codecov && codecov
services:
  - mysql
